services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5174:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: ./backend
    ports:
      - "8010:8000"
    volumes:
      - ./backend:/app

